defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: rails3_mongoid_devise_development

test:
  <<: *defaults
  database: rails3_mongoid_devise_test

# set these environment variables on your prod server

staging:
  host: 10.10.0.1
  port: 27017    

production:
  host: 10.10.0.1
  port: 27017